CREATE OR ALTER PROC FI_SP_ConsCliente    
 @ID BIGINT    
AS    
BEGIN    
 IF(ISNULL(@ID,0) = 0)    
  SELECT C.*, B.ID AS 'B_ID', B.CPF AS 'B_CPF', B.NOME AS 'B_NOME' FROM CLIENTES AS C WITH(NOLOCK)     
  LEFT JOIN BENEFICIARIOS AS B WITH(NOLOCK) ON B.IDCLIENTE = C.ID    
 ELSE    
  SELECT C.*, B.ID AS 'B_ID', B.CPF AS 'B_CPF', B.NOME AS 'B_NOME' FROM CLIENTES AS C WITH(NOLOCK)     
  LEFT JOIN BENEFICIARIOS AS B WITH(NOLOCK) ON B.IDCLIENTE = C.ID    
  WHERE C.ID = @ID    
END